services:
  - type: web
    name: jagdamba-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: MaaJagdambaSamiti
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
